version: '3'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel
    restart: on-failure:5
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage

  nginx:
    image: nginx:alpine
    restart: on-failure:5
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - laravel

  postgres:
    image: postgres:15.4-alpine
    restart: on-failure:5
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PG_HOST=${DB_HOST}
      - PG_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TIMEZONE}

volumes:
  postgres-data: 